# Inventory filter mod info messages

{100}{}{The trader was automatically offered %d more batteries.}
{101}{}{Action not possible: close the bag first.}

{102}{}{Inventory Filter: not compatible with the current version of sfall.}
{103}{}{Inventory Filter: requires a screen resolution at least 740 pixels wide.}

{104}{}{Filter is off. Press F11 to turn it on.}
{105}{}{Filter on.}
{106}{}{Filter off.}

{107}{}{: is too far away to trade with.}
{108}{}{You cannot switch to a companion for trading while the filter is on.}

{110}{}{Melee Weapons}
{111}{}{Firearms}
{112}{}{Ammo}
{113}{}{Armor}
{114}{}{Drugs}
{115}{}{Tools}
{116}{}{Misc}
